[2024-09-13T10:00:04.471+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-13T10:00:04.481+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.training_model_C manual__2024-09-13T09:59:57.626403+00:00 [queued]>
[2024-09-13T10:00:04.486+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.training_model_C manual__2024-09-13T09:59:57.626403+00:00 [queued]>
[2024-09-13T10:00:04.486+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-13T10:00:04.508+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): training_model_C> on 2024-09-13 09:59:57.626403+00:00
[2024-09-13T10:00:04.511+0000] {standard_task_runner.py:72} INFO - Started process 7227 to run task
[2024-09-13T10:00:04.514+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'first_dag', 'training_model_C', 'manual__2024-09-13T09:59:57.626403+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp1sjo_b5k']
[2024-09-13T10:00:04.514+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask training_model_C
[2024-09-13T10:00:04.555+0000] {task_command.py:467} INFO - Running <TaskInstance: first_dag.training_model_C manual__2024-09-13T09:59:57.626403+00:00 [running]> on host ip-172-31-23-215.ec2.internal
[2024-09-13T10:00:04.614+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='training_model_C' AIRFLOW_CTX_EXECUTION_DATE='2024-09-13T09:59:57.626403+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-13T09:59:57.626403+00:00'
[2024-09-13T10:00:04.614+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-13T10:00:04.615+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-13T10:00:04.615+0000] {logging_mixin.py:190} INFO - Current task name:training_model_C state:running start_date:2024-09-13 10:00:04.481958+00:00
[2024-09-13T10:00:04.615+0000] {logging_mixin.py:190} INFO - Dag name:first_dag and current dag run status:running
[2024-09-13T10:00:04.615+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-13T10:00:04.616+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow/dags/first_dag.py", line 8, in _training_model
    return randit(1,10)
           ^^^^^^
NameError: name 'randit' is not defined. Did you mean: 'randint'?
[2024-09-13T10:00:04.621+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-13T10:00:04.621+0000] {logging_mixin.py:190} INFO - Task start:2024-09-13 10:00:04.481958+00:00 end:2024-09-13 10:00:04.621344+00:00 duration:0.139386
[2024-09-13T10:00:04.621+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): training_model_C> dag:<DAG: first_dag> dagrun:<DagRun first_dag @ 2024-09-13 09:59:57.626403+00:00: manual__2024-09-13T09:59:57.626403+00:00, state:running, queued_at: 2024-09-13 09:59:57.656489+00:00. externally triggered: True>
[2024-09-13T10:00:04.622+0000] {logging_mixin.py:190} INFO - Failure caused by name 'randit' is not defined
[2024-09-13T10:00:04.622+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=first_dag, task_id=training_model_C, run_id=manual__2024-09-13T09:59:57.626403+00:00, execution_date=20240913T095957, start_date=20240913T100004, end_date=20240913T100004
[2024-09-13T10:00:04.636+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-13T10:00:04.636+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 15 for task training_model_C (name 'randit' is not defined; 7227)
Traceback (most recent call last):
  File "/home/ubuntu/airflow-env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-env/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-env/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-env/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ubuntu/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow/dags/first_dag.py", line 8, in _training_model
    return randit(1,10)
           ^^^^^^
NameError: name 'randit' is not defined. Did you mean: 'randint'?
[2024-09-13T10:00:04.648+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-13T10:00:04.659+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-13T10:00:04.660+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
